name: NeoGen Assistant
version: 1.0.0
schema: v1
models:
  - name: NeoGen Multimodal M
    provider: openai
    model: neogen-multimodal-m
    apiKey: ${{API_KEY}}
    apiBase: https://neogen.neosoft.fr/api/
    env:
      useLegacyCompletionsEndpoint: false
    roles:
      - chat
      - edit

  - name: NeoGen Coder M
    provider: openai
    model: neogen-coder-m
    apiKey: ${{API_KEY}}
    apiBase: https://neogen.neosoft.fr/api/
    env:
      useLegacyCompletionsEndpoint: false
    roles:
      - chat
      - edit
	  
  - name: NeoGen Raisonnement L
    provider: openai
    model: neogen-raisonnement-l
    apiKey: ${{API_KEY}}
    apiBase: https://neogen.neosoft.fr/api/
    env:
      useLegacyCompletionsEndpoint: false
    roles:
      - chat
      - edit
 
  - name: NeoGen Coder XS 
    provider: openai
    model: neogen-coder-xs
    apiKey: ${{API_KEY}}
    apiBase: https://neogen.neosoft.fr/api/
    env:
      useLegacyCompletionsEndpoint: false
    roles:
      - autocomplete

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
